### ISSUE TITLE
Card Component 리팩토링하기

### ISSUE THREAD

**Issue by rldnrl** [rldnrl-tutorial/t3-bookmark-app#8]
# ✏️ TODO
- [x] CardDetail에서 CardDescription으로 변경
- [x] CardLink 컴포넌트 추가
- [x] CardBody 컴포넌트 추가
- [x] Next Image가 아닌 그냥 `img` 태그로 변경(Next Image를 사용하기 위해서는 `next.config.js`에서 도메인을 등록해줘야하는데, S3를 사용하고 있지 않은 상태로 일단 기본 `img` 태그 사용)
